#include "version.h"

// The following header file is autogenerated by version.cmake, and will export
// a definition of the current git version for the build
#include "gen_versionnumber.h"

namespace OpenNetlistView {

QString getDiagViewerVersion()
{
    return QString{DIAGVIEWER_GIT_VERSION};
}

} // namespace OpenNetlistView
