services:
  diag_viewer:
    image: diag_image:latest
    container_name: diag_container
    hostname: diag_container
    command: bash
    working_dir: /home/user/diag_viewer
    volumes:
      # gui support
      - /tmp/.X11-unix:/tmp/.X11-unix
      # audio (uncimmnet if audio is needed)
      # - ~/.config/pulse/cookie:/root/.config/pulse/cookie
      # - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      # time
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # work directory (needs to be set)
      - ./:/home/user/diag_viewer
      # .ssh for git access (uncomment for git access over ssh in container)
      # NOTE: Any user that is in the docker group can access the host's ssh keys.
      # - ~/.ssh:/home/user/.ssh
      # Mount further directories from host system here ...

    ports:
      - "8000:8000" # for webserver

    environment:
      # gui support
      DISPLAY: $DISPLAY
      QT_SCALE_FACTOR: 1.0
      QT_DIR: "/opt/qt/gcc_64" # for qt native
      # QT_DIR: "/opt/qt/wasm_singlethread" # for qt wasm
      # audio
      ALSA_CARD: 1 # card from cmd 'aplay -l'
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native # pulse audio for sound
      # LD_LIBRARY_PATH: "/opt/qt/gcc_64/lib:$LD_LIBRARY_PATH" # for qt
    devices:
      - "/dev/dri:/dev/dri" # gui support
      - "/dev/snd:/dev/snd" # sound support
    privileged: true # used for external usb devices like headset. Maybe also for external monitors.
    stdin_open: true # docker run -i
    tty: true # docker run -t
